hyperskill_project:
  id: 155
  ide_files: https://stepik.org/media/attachments/lesson/472772/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 808
  step: 12058
  is_completed: true
- id: 809
  step: 12059
  is_completed: true
- id: 810
  step: 12060
  is_completed: true
- id: 811
  step: 12061
  is_completed: true
- id: 812
  step: 12062
  is_completed: true
topics:
  0:
  - title: Introduction to Python
    theory_id: 5204
  - title: Overview of the basic program
    theory_id: 5208
  - title: Multi-line programs
    theory_id: 5233
  - title: PEP 8
    theory_id: 5879
  - title: Comments
    theory_id: 6081
  - title: Taking input
    theory_id: 5913
  - title: Naming variables
    theory_id: 5885
  - title: Program with numbers
    theory_id: 5872
  - title: If statement
    theory_id: 5953
  - title: Else statement
    theory_id: 5932
  - title: Basic data types
    theory_id: 5852
  - title: Variables
    theory_id: 5859
  - title: Integer arithmetic
    theory_id: 5865
  - title: Boolean logic
    theory_id: 6025
  - title: Comparisons
    theory_id: 5920
  - title: Quotes and multi-line strings
    theory_id: 5814
  - title: String formatting
    theory_id: 6037
  1:
  - title: Computer programming
    theory_id: 8739
  - title: Introduction to OOP
    theory_id: 3614
  - title: Load module
    theory_id: 6019
  - title: Class
    theory_id: 6661
  - title: Class instances
    theory_id: 6669
  - title: For loop
    theory_id: 6065
  - title: Methods
    theory_id: 6931
  - title: Methods and attributes
    theory_id: 6981
  - title: Program execution
    theory_id: 6047
  - title: Errors
    theory_id: 6052
  - title: Exceptions
    theory_id: 6042
  - title: Regexps basics
    theory_id: 7580
  - title: Regexps in Python
    theory_id: 9468
  - title: Escaping in regexps
    theory_id: 9754
  - title: Regexp sets and ranges
    theory_id: 10035
  - title: Shorthands
    theory_id: 10142
  - title: Regexp quantifiers
    theory_id: 10355
  - title: Match object and flags
    theory_id: 12902
  - title: Regexp functions in Python
    theory_id: 14180
  - title: Invoking a function
    theory_id: 5891
  - title: Declaring a function
    theory_id: 5900
  - title: Scopes
    theory_id: 6322
  - title: List
    theory_id: 5979
  - title: Arguments
    theory_id: 7248
  - title: Indexes
    theory_id: 6189
  - title: Identity testing
    theory_id: 8077
  - title: Basic string methods
    theory_id: 6842
  - title: Escape sequences
    theory_id: 7130
  - title: Split and join
    theory_id: 6972
  - title: Operations with list
    theory_id: 6031
  - title: Conversion to boolean
    theory_id: 10327
  - title: Tuple
    theory_id: 7462
  - title: Slicing
    theory_id: 6177
  2:
  - title: Introduction to Operating systems
    theory_id: 9704
  - title: Files
    theory_id: 13025
  - title: File types
    theory_id: 13017
  - title: Command line overview
    theory_id: 8977
  - title: Parameters and Options
    theory_id: 9746
  - title: Command line arguments
    theory_id: 7981
  - title: Argparse module
    theory_id: 11389
  - title: Introduction to Linux
    theory_id: 9526
  - title: File modes and permissions
    theory_id: 13953
  - title: Working with file modes and permissions
    theory_id: 13961
  - title: Files in Python
    theory_id: 8691
  - title: Reading files
    theory_id: 8139
  - title: Type casting
    theory_id: 6224
  - title: Dictionary
    theory_id: 6481
  3:
  - title: Math functions
    theory_id: 6256
